version: '3.9'

services:
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${API_PORT}/healthcheck || exit 1 "
        ]
      interval: 5s
      timeout: 60s
      retries: 3
      start_period: 5s
